# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa06b47c40ab5bffd716f996c7ec0a4ad281758d807dcbc5e64d3c82cded000522889aa4a2e1248e9c218e80afbe8054e6358b58fb9f4c3278fafd643befcd0f

test:
  secret_key_base: 28c287f542445ca2b5b866b88d12cf86cf0ab0fa329061b27fce2ab5b6c7c467ce6bd3ad4f9003ed09193e59056a774c3230f228dd681f2becdabac8457f580d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
